apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-example-cronjob
spec:
           # ┌───────────── minute (0 - 59)
           # │ ┌───────────── hour (0 - 23)
           # │ │ ┌───────────── day of the month (1 - 31)
           # │ │ │ ┌───────────── month (1 - 12)
           # │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
           # │ │ │ │ │                                   7 is also Sunday on some systems)
           # │ │ │ │ │                                   OR sun, mon, tue, wed, thu, fri, sat
           # │ │ │ │ │
           # * * * * *
  schedule: "* * * * *" #	Run every minute
# schedule: "0 * * * *" #	Run every hour at **:00
# schedule: "*/5 * * * *" #	Run every 5 minutes
  jobTemplate:
    spec: # job spec
      template:
        spec: # pod spec
          containers:
            - name: cronjob-container
              image: busybox:latest
              command:
                - /bin/sh
                - -c
                - date; echo Hello!
          restartPolicy: Never
