apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo-app.name" . }}
  labels:
    app: {{ include "echo-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "echo-app.name" . }}
  template:
    metadata:
      name: {{ include "echo-app.name" . }}
      labels:
        app: {{ include "echo-app.name" . }}
    spec:
      containers:
        - name: {{ .Values.image.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.port }}
              name: {{ .Values.portName }}
          env:
            - name: PORT
              value: "{{ .Values.port }}"
