apiVersion: v2
name: jacek-echo-app
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: 12.5.8
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 12.5.8
    repository: https://charts.bitnami.com/bitnami
    alias: postgres2
