echoApp:
  name: webserver
  replicaCount: 1
  image:
    containerName: echo-server
    repository: jmalloc/echo-server
    tag: latest
  port: 8123
  portName: echo-port

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: alb
    annotations: {
      alb.ingress.kubernetes.io/target-type: ip,
      alb.ingress.kubernetes.io/scheme: internet-facing
    }
    hosts:
      - host: jacek-echo-app.k8s-training.brightinventions.pl
        paths:
          - path: /
            pathType: Prefix

curlCronjob:
  schedule: "* * * * *"
  image:
    repository: curlimages/curl
    tag: 8.1.1
  restartPolicy: Never
  ttlSecondsAfterFinished: 120
  activeDeadlineSeconds: 60
  backoffLimit: 2

postgresql:
  nameOverride: "Postgres1"
  architecture: standalone

postgres2:
  nameOverride: "Postgres2"
  architecture: standalone
